# Generated by Django 2.2.6 on 2019-10-18 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20191018_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='href',
        ),
    ]
