# Generated by Django 2.2.6 on 2019-10-22 09:51

import challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0003_remove_challenge_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='file',
            field=models.FileField(null=True, upload_to=challenge.models.challenge_file_path),
        ),
    ]
