# Generated by Django 2.2.6 on 2019-10-22 09:55

import challenge.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_auto_20191022_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='filepath',
            field=models.FilePathField(null=True, path=challenge.models.challenge_file_path),
        ),
    ]
