# Generated by Django 2.2.6 on 2019-10-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_challenge_filepath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='filepath',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='file',
            field=models.FileField(null=True, upload_to='ChallengeFiles/'),
        ),
    ]
