# Generated by Django 2.2.6 on 2019-10-28 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20191027_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whofinishme',
            name='finishedTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
