# Generated by Django 2.2.6 on 2019-10-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20191028_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='finishedtimes',
            field=models.IntegerField(default=0),
        ),
    ]
