# Generated by Django 2.2.5 on 2019-10-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='The student id of the user'),
        ),
    ]
