# Generated by Django 2.2.5 on 2019-10-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(default=0, max_length=20, null=True, verbose_name='The student id of the user'),
        ),
    ]
