# Generated by Django 2.2.5 on 2019-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191024_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ismanager',
        ),
        migrations.AddField(
            model_name='user',
            name='issuperuser',
            field=models.BooleanField(default=False, verbose_name='is it a team manager'),
        ),
        migrations.AddField(
            model_name='user',
            name='mark',
            field=models.IntegerField(default=0),
        ),
    ]
