# Generated by Django 2.2.5 on 2019-10-26 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20191025_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': '团队'},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='mark',
            new_name='score',
        ),
    ]
