# Generated by Django 2.2.5 on 2019-10-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_applymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
