# Generated by Django 2.2.5 on 2019-10-27 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_team_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applymessage',
            old_name='apply_time',
            new_name='apply_date',
        ),
        migrations.AlterField(
            model_name='applymessage',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliesreceived', to='user.User'),
        ),
        migrations.AlterField(
            model_name='applymessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliessent', to='user.User'),
        ),
    ]
