# Generated by Django 2.2.5 on 2019-10-27 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20191027_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymessage',
            name='apply_state',
            field=models.CharField(choices=[('approved', '通过'), ('rejected', '拒绝'), ('unchecked', '待审核')], default='unchecked', max_length=20),
        ),
    ]
