# Generated by Django 2.2.5 on 2019-10-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_applymessage_apply_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymessage',
            name='apply_state',
            field=models.CharField(choices=[('approved', '通过'), ('denied', '拒绝'), ('unchecked', '待审核')], default='unchecked', max_length=20),
        ),
    ]
