# Generated by Django 2.2.5 on 2019-10-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20191027_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='applymessage',
            name='team',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
