# Generated by Django 2.2.5 on 2019-10-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_applymessage_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymessage',
            name='team',
            field=models.CharField(default='', max_length=20),
        ),
    ]
