# Generated by Django 2.2.5 on 2019-10-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20191027_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymessage',
            name='team',
            field=models.CharField(default='', max_length=20, verbose_name='desired team'),
        ),
    ]
