# Generated by Django 2.2.6 on 2019-11-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20191027_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='right_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='submit_num',
            field=models.IntegerField(default=0),
        ),
    ]
