# Generated by Django 2.2.6 on 2019-11-07 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20191107_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='default', max_length=10, verbose_name="The user's real_name"),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='The student id of the user'),
        ),
    ]
