# Generated by Django 2.2.5 on 2019-11-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_kickedmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mark',
            new_name='score',
        ),
    ]
