# Generated by Django 2.2.5 on 2019-11-07 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20191107_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='kickedmessage',
            name='team',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='kickedmessage',
            name='kickeduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kickedmessage', to='user.User'),
        ),
    ]
