# Generated by Django 2.2.6 on 2019-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20191107_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.IntegerField(unique=True, verbose_name='The student id of the user'),
        ),
    ]
