# Generated by Django 2.2.5 on 2019-11-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20191107_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymessage',
            name='apply_state',
            field=models.CharField(choices=[('approved', '通过'), ('denied', '拒绝'), ('unchecked', '待审核'), ('invalid', '无效了')], default='unchecked', max_length=20),
        ),
    ]
