# Generated by Django 2.2.6 on 2019-11-07 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20191107_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applymessage',
            name='apply_state',
            field=models.CharField(choices=[('approved', '通过'), ('denied', '拒绝'), ('unchecked', '待审核'), ('invalid', '无效了')], default='unchecked', max_length=20),
        ),
        migrations.CreateModel(
            name='KickedMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(default='no reason', max_length=20)),
                ('team', models.CharField(default='', max_length=20)),
                ('kickeduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kickedmessage', to='user.User')),
            ],
        ),
    ]
